name: Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker meta (worker)
        id: metaworker
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/joschahenningsen/tum-live-worker-v2/worker
          tags: |
            type=sha
          flavor: |
            latest=true
      - name: Docker meta (nginx)
        id: metanginx
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/joschahenningsen/tum-live-worker-v2/nginx
          tags: |
            type=sha
          flavor: |
            latest=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push Docker images (nginx)
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          build-args: version=${{ steps.vars.outputs.sha_short }}
          tags: ${{ steps.metaworker.outputs.tags }}
          labels: ${{ steps.metaworker.outputs.labels }}
      - name: Build and push Docker images (worker)
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          pull: true
          push: true
          build-args: version=${{ steps.vars.outputs.sha_short }}
          tags: ${{ steps.metanginx.outputs.tags }}
          labels: ${{ steps.metanginx.outputs.labels }}
